### ISSUE TITLE
Test suite fails on Maya 2017

### ISSUE THREAD

**Issue by bfloch** [Autodesk/animx#1]
Hi,

We get 0 errors for Maya-2014, but about ~890 errors for Maya-2017.
If the precision is reduced to 4 digits we get ~200 errors and with 3 digits only one.

We're interested to know if something changed internally in Maya that needs to be compensated in the library and if there are any guarantees that prevent this to happen in future. Or is the difference just a shortcoming of the test suite?

Cheers,
Blazej

**Comment by bfloch** [comment]
Hi @rein4ce,

We actually compared curves between Maya 2014 and 2017. The described problem applies to them, too. Meaning the precision error/difference happens between Maya 2014 to 2017.

So based on that observation animx is based on Maya 2014's model/implementation, and in itself does not comply to later Maya versions. We're curious to understand what changed. Or is this a bug?

**Comment by rein4ce** [comment]
Hello Blazej,

Maya 2017 has introduced 64-bit time precision mode which is enabled by
default. This mode does indeed cause minor precision differences in the
curve evaluation compares to past Maya releases, hence we expose a build
flag for animX that builds it with or without 64 bit precision.

cmake -DMAYA_VERSION=2017 -DMAYA_64BIT_TIME_PRECISION=1 .

More info in the README.md file.

For further questions, please reach out to mdelasa (
https://github.com/mdelasa) who manages the project now.

Cheers,
Michal Domanski

**Comment by bfloch** [comment]
Thanks for the quick reply.
